# Generated by Django 5.1.3 on 2024-11-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venue",
            old_name="capacity",
            new_name="Capacity",
        ),
    ]
