# Generated by Django 5.1.3 on 2024-11-11 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_capacity_venue_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="Type",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="poster",
            field=models.ImageField(default="default.jpg", upload_to="service_img"),
        ),
        migrations.AddField(
            model_name="venue",
            name="Poster",
            field=models.ImageField(null=True, upload_to="Venue_img"),
        ),
    ]
