# Generated by Django 5.1.3 on 2024-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_service_type_service_poster_venue_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="keywords",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="Description",
            field=models.CharField(max_length=1000),
        ),
    ]
