# Generated by Django 5.1.3 on 2024-11-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_service_keywords_alter_service_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                (
                    "poster",
                    models.ImageField(default="default.jpg", upload_to="Our Work"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
