# Generated by Django 5.1.3 on 2024-11-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.service",
                    ),
                ),
                (
                    "Venue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.venue",
                    ),
                ),
            ],
        ),
    ]
