# Generated by Django 5.1.3 on 2024-11-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_plannerlist_service_alter_plannerlist_venue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plannerlist",
            old_name="Booked_at",
            new_name="booked_at",
        ),
        migrations.RenameField(
            model_name="plannerlist",
            old_name="Service",
            new_name="service",
        ),
        migrations.RenameField(
            model_name="plannerlist",
            old_name="Venue",
            new_name="venue",
        ),
    ]
