# Generated by Django 5.1.3 on 2024-11-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerlist",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plannerlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.user",
            ),
        ),
    ]
