# Generated by Django 5.1.3 on 2024-11-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_plannerlist_session_id_plannerlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerlist",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.package",
            ),
        ),
    ]
