# Generated by Django 5.1.3 on 2024-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_plannerlist_user_profile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
